sandthorn_product_example/config/routes.rb
SandthornProductExample::Application.routes.draw do
  get "products/index"
  get "products/new"
  get "products/update"
  get "products/destroy"
  get "products/create"
  get "products/show"
  root "welcome#index"

  #actice record product routes
  resources :products

  namespace :sandthorn do
    get "log"
    resources :products do
      post :change_name
      post :change_price
      post :in_stock
      post :out_of_stock
      post :discontinue
      post :put_on_sale
      post :remove_from_sale
    end
  end

  match "/sandthorn/log" => "sandthorn_products_tasked_based#get_log", :via => "get"
end

sandthorn_product_example/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sandthorn Product Example</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <%= nav_link 'Home', root_path %>
          <%= nav_link 'AR Products', products_path %>
          <%= nav_link 'Sandthorn Products', sandthorn_products_path %>
        </ul>
        <h3 class="text-warning"><a href="https://github.com/Sandthorn/" target="_blank">Sandthorn</a> Product Example</h3>
      </div>

      <%= yield %>

      <div class="footer">
        <div class="row">
          <div class="col-sm-6"><p><a href="https://github.com/Sandthorn" target="_blank"><span class="glyphicon glyphicon-user"></span> Sandthorn Event Sourcing</a></p></div>
          <div class="col-sm-6"><p class="pull-right"><a href="mailto:info@sandthorn.org" target="_blank"><span class="glyphicon glyphicon-envelope"></span> info@sandthorn.org</a></p></div>
        </div>

      </div>

    </div> <!-- /container -->
  </body>
</html>