sandthorn_product_example/config/routes.rb
SandthornProductExample::Application.routes.draw do
  get "products/index"
  get "products/new"
  get "products/update"
  get "products/destroy"
  get "products/create"
  get "products/show"
  root "welcome#index"

  #actice record product routes
  resources :products

  namespace :sandthorn do
    get "log"
    resources :products do
      post :change_name
      post :change_price
      post :in_stock
      post :out_of_stock
      post :discontinue
      post :put_on_sale
      post :remove_from_sale
    end
  end

  match "/sandthorn/log" => "sandthorn_products_tasked_based#get_log", :via => "get"
end

sandthorn_product_example/app/models/product.rb
class Product < ActiveRecord::Base

  validates :name, presence: true

end

sandthorn_product_example/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :log

  def new
    @product = Product.new
  end

  def index
    @products = Product.all
  end

  def create
    @product = Product.new product_params
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find params[:id]
  end

  def update
    @product = Product.find(params[:id])
 
    if @product.update(params[:product].permit(:name, :price, :stock_status))
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
   
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :price, :stock_status)
  end

  def log
    sql = "select * from products"
    @log = ActiveRecord::Base.connection.execute(sql)
  end

end

sandthorn_product_example/app/controllers/sandthorn/products_controller.rb
module Sandthorn
  class ProductsController < ApplicationController

    before_action :log
    skip_before_filter :verify_authenticity_token

    def new
      #@product = SandthornProduct.new
    end

    def index
      @products = SandthornProduct.all.select { |product| product.active == true }
    end

    def create
      SandthornProduct.aggregate_trace trace_info do
        @product = SandthornProduct.new product_params
      end
      if @product.save
        redirect_to "/sandthorn/product/#{@product.id}"
      else
        render 'new'
      end
    end

    def show
      @product = SandthornProduct.find(params[:id])
    end

    def edit
      @product = SandthornProduct.find params[:id]
    end

    def update
      @product = SandthornProduct.find(params[:id])

      @product.aggregate_trace trace_info do |aggregate|

        aggregate.update_name product_params[:name]
        aggregate.update_price product_params[:price]
        puts aggregate.stock_status
        puts product_params[:stock_status]
        aggregate.update_stock_status product_params[:stock_status]
        puts aggregate.stock_status
        aggregate.put_on_sale if product_params[:on_sale] == "true"
        aggregate.remove_from_sale if product_params[:on_sale] == "false"

      end
      @product.save

      redirect_to sandthorn_product_path(@product.id)
    end

    def destroy
      @product = SandthornProduct.find(params[:id])
      @product.destroy
      @product.save

      redirect_to "/sandthorn/products/index"
    end

    private
    def product_params
      params.require(:sandthorn_product).permit(:name, :price, :stock_status, :on_sale)
    end

    def trace_info
      trace_info = {ip: request.remote_ip}
    end

  end

end

sandthorn_product_example/app/helpers/products_helper.rb
module ProductsHelper
end

sandthorn_product_example/app/views/sandthorn/products/_form.html.erb
<!-- <form accept-charset="UTF-8" action="/sandthorn/product/<%= @product.id %>/update" method="post">
  <div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"></div>

  <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

  <p>
    <label for="sandthorn_product_name">Name</label><br>
    <input id="sandthorn_product_name" name="sandthorn_product[name]" type="text" value="<%= @product.name %>">
  </p>

  <p>
    <label for="sandthorn_product_price">Price</label><br>
    <input id="sandthorn_product_price" name="sandthorn_product[price]" type="text" value="<%= @product.price %>">
  </p>

  <p>
    <label for="sandthorn_product_stock_status">Stock status</label><br>
    <input <%= 'checked' if @product.stock_status == 'instock' %> id="sandthorn_product_stock_status_instock" name="sandthorn_product[stock_status]" type="radio" value="instock">
    <label for="sandthorn_product_stock_status_instock">In stock</label>
    <input <%= 'checked' if @product.stock_status == 'outofstock' %> id="sandthorn_product_stock_status_outofstock" name="sandthorn_product[stock_status]" type="radio" value="outofstock">
    <label for="sandthorn_product_stock_status_outofstock">Out of stock</label>
    <input <%= 'checked' if @product.stock_status == 'discontinued' %> id="sandthorn_product_stock_status_discontinued" name="sandthorn_product[stock_status]" type="radio" value="discontinued">
    <label for="sandthorn_product_stock_status_discontinued">Discontinued</label>
  </p>

  <p>
    <input name="commit" type="submit" value="Update">
  </p>
</form> -->

sandthorn_product_example/app/views/sandthorn/products/_log.html.erb
<h4>Event Sourced database</h4>

<h5>Aggregates table</h5>
<div class="table-responsive">
    <table id="event_table" class="table table-striped table-condensed">
    	<thead>
    		<tr>
    			<th>
    			aggregate_type
    			</th>
    			<th>
    			aggregate_id
    			</th>
    			<th>
    			current version
    			</th>
    		</tr>
    	</thead>
    	<tbody>
    <% @aggregate_log.each do |row| %>
      	<tr class="info">
      		<td><%=row["aggregate_type"] %></td>
      		<td><%=row["aggregate_id"] %></td>
    			<td><%=row["aggregate_version"] %></td>
     		</tr>
    <% end %>
    	</tbody>
    </table>
</div>
<br>

<h5>Events, a bit humanized, newest first</h5>
<div class="table-responsive">
    <table id="event_table" class="table table-striped table-condensed">
    	<thead>
    		<tr>
    			<th class="text-center">
    				<div class="vertical-text">
            	<div class="vertical-text-inner">
                sequence_number
              </div>
            </div>
        	</th>
    			<th class="text-center">
    				<div class="vertical-text">
            	<div class="vertical-text-inner">
                aggregate_type
              </div>
            </div>
        	</th>
    			<th class="text-center">
    				<div class="vertical-text">
            	<div class="vertical-text-inner">
                aggregate_id
              </div>
            </div>
        	</th>
    			<th class="text-center">
    				<div class="vertical-text">
            	<div class="vertical-text-inner">
                aggregate_version
              </div>
            </div>
        	</th>
    			<th class="text-center">
    				<div class="vertical-text">
            	<div class="vertical-text-inner">
                event_name
              </div>
            </div>
        	</th>
    			<th class="text-center">
    				<div class="vertical-text">
            	<div class="vertical-text-inner">
                event_data
              </div>
            </div>
        	</th>
        	</tr>
    	</thead>
    	<tbody>
    	<% @event_log.reverse.each do |row| %>
      	<tr class="success">
      		<td><%=row[:sequence_number] %></td>
      		<td><%=row[:aggregate_type] %></td>
      		<td><%=row[:aggregate_id] %></td>
      		<td><%=row[:aggregate_version] %></td>
      		<td>:<%=row[:event_name] %></td>
      		<td>
            <button type="button" class="btn btn-success btn-xs show" id="<%=row[:sequence_number] %>" >Show event data</button>
            <button type="button" class="btn btn-warning btn-xs btn-block hidden">Hide event data</button>
            <div id="div_<%=row[:sequence_number] %>" class="event_data hidden">
              <%= raw humanized_event_data({timestamp: row[:timestamp].getlocal}.merge(row[:event_args]))%>
            </div>
          </td>
      	</tr>
    	<% end %>
    	</tbody>
    </table>
</div>
<br />

<h5>Raw events table, oldest first</h5>
<% @event_log.each do |row| %>
  <p class="bg-warning"><%= row %></p>
<% end %>

<h5>Snapshots table</h5>
<div class="table-responsive">
    <table class="table table-striped table-condensed">
    	<thead>
    		<th class="text-center">
    				<div class="vertical-text">
            	<div class="vertical-text-inner">
                aggregate_type
              </div>
            </div>
        	</th>
    			<th class="text-center">
    				<div class="vertical-text">
            	<div class="vertical-text-inner">
                aggregate_id
              </div>
            </div>
        	</th>
    			<th class="text-center">
    				<div class="vertical-text">
            	<div class="vertical-text-inner">
                snapshotted at version
              </div>
            </div>
        	</th>
    			<th class="text-center">
    				<div class="vertical-text">
            	<div class="vertical-text-inner">
                current real version
              </div>
            </div>
        	</th>
    			<th class="text-center">
    				<div class="vertical-text">
            	<div class="vertical-text-inner">
                yaml snapshot
              </div>
            </div>
        	</th>
    	</thead>
    	<tbody>
    <% @snapshots_log.each do |row| %>
      	<tr class="danger">
      		<td><%=row["aggregate_type"] %></td>
      		<td><%=row["aggregate_id"] %></td>
    			<td><%=row["snapshot_version"] %></td>
    			<td><%=row["current_version"] %></td>
    			<td><button type="button" class="btn btn-danger btn-xs btn-block show">Show yaml data</button><button type="button" class="btn btn-warning btn-xs btn-block hidden">Hide yaml data</button><div class="event_data hidden"><%=row["snapshot_data"]%></div></td>
     		</tr>
    <% end %>

    	</tbody>
    </table>
</div>
<script type="text/javascript">
	$(window).ready(function(){
		$("table button").on("click", function(e){
			var notify = function(id) {
				console.log("#div_"+id);
				setTimeout(function() {
				var n = $("<div class='notify'>Showing this event data</div>").appendTo("#div_"+id);
				setTimeout(function() { n.remove(); }, 2500);
				}, 250);
			};
			console.log(this.id);
			show = $(this).parent().find(".hidden");
			hide = $(this).parent().find(".show");
			show.removeClass("hidden").addClass("show");
			hide.removeClass("show").addClass("hidden");
			$(this).parent().scrollintoview({ duration: "normal", complete: notify(this.id) });
		});
	});

</script>

sandthorn_product_example/app/views/sandthorn/products/edit.html.erb
<div class="row editing">
    <div class="col-sm-12">
        <h2>Editing Sandthorn product</h2>

        <%= form_tag(sandthorn_product_path(@product.id), method: :put) do %>

        <div class="jumbotron clearfix">
            <div class="form-group clearfix">
                <label for="sandthorn_product_name" class="col-sm-3 ">Name</label>
                <div class="col-sm-9">
                    <input id="sandthorn_product_name" name="sandthorn_product[name]" type="text" class="form-control" placeholder="Name" value="<%= @product.name %>">
                </div>
            </div>
            <div class="form-group clearfix">
                <label for="sandthorn_product_price" class="col-sm-3 ">Price</label>
                <div class="col-sm-9">
                    <input id="sandthorn_product_price" name="sandthorn_product[price]" type="text" class="form-control" placeholder="Price" value="<%= @product.price %>">
                </div>
            </div>
            <div class="form-group clearfix">
                <label class="col-sm-3 ">Stock Status</label>
                <div class="col-sm-9">
                    <div class="btn-group btn-group-sm stock-status" data-toggle="buttons">
                        <label id="sandthorn_product_stock_status_instock_label" class="btn btn-<%= 'success active' if @product.stock_status == 'instock' %><%= 'default' if @product.stock_status != 'instock' %>">
                        <span class="glyphicon glyphicon-ok-circle"></span>
                            <input <%= 'checked' if @product.stock_status == 'instock' %> id="sandthorn_product_stock_status_instock" class="stock_status" name="sandthorn_product[stock_status]" type="radio" value="instock"> In stock
                        </label>
                        <label  id="sandthorn_product_stock_status_outofstock_label" class="btn btn-<%= 'warning active' if @product.stock_status == 'outofstock' %><%= 'default' if @product.stock_status != 'outofstock' %>">
                        <span class="glyphicon glyphicon-ban-circle"></span>
                            <input <%= 'checked' if @product.stock_status == 'outofstock' %> id="sandthorn_product_stock_status_outofstock" class="stock_status" name="sandthorn_product[stock_status]" type="radio" value="outofstock"> Out of stock
                        </label>
                        <label id="sandthorn_product_stock_status_discontinued_label" class="btn btn-<%= 'danger active' if @product.stock_status == 'discontinued' %><%= 'default' if @product.stock_status != 'discontinued' %>">
                        <span class="glyphicon glyphicon-remove-circle"></span>
                            <input <%= 'checked' if @product.stock_status == 'discontinued' %> id="sandthorn_product_stock_status_discontinued" class="stock_status" name="sandthorn_product[stock_status]" type="radio" value="discontinued"> Discontinued
                        </label>
                    </div>
                </div>
            </div>

            <div class="form-group clearfix">
                <label class="col-sm-3 ">On Sale</label>
                <div class="col-sm-9">
                     <div class="btn-group btn-group-sm on-sale" data-toggle="buttons">

                         <label  id="sandthorn_product_on_sale_true_label" class="btn btn-<%= 'success  active' if @product.on_sale %><%= 'default' if !@product.on_sale %>" for="sandthorn_product_on_sale_true">
                         <span class="glyphicon glyphicon-ok-circle"></span>
                            <input <%= 'checked' if @product.on_sale %> id="sandthorn_product_on_sale_true" name="sandthorn_product[on_sale]" type="radio" value="true">Yes</label>

                        <label  id="sandthorn_product_on_sale_false_label" class="btn btn-<%= 'danger  active' if !@product.on_sale %><%= 'default' if @product.on_sale %>" for="sandthorn_product_on_sale_false">
                        <span class="glyphicon glyphicon-ban-circle"></span>
                            <input <%= 'checked' if !@product.on_sale %> id="sandthorn_product_on_sale_false" name="sandthorn_product[on_sale]" type="radio" value="false">No</label>
                    </div>

                </div>
            </div>

            <div class="col-sm-3">
            </div>
            <div class="col-sm-9">
                <input id="update_button" name="commit" type="submit" value="Update Product" class="btn btn-success">
                <label  class="btn btn-default pull-right">Ajax update
                    <input id="tasked_based" type="checkbox"></label>
            </div>
        </div>
        <% end %>

        <%= link_to sandthorn_product_path(@product.id), class: "btn btn-sm btn-primary"  do %>
          <span class="glyphicon glyphicon-chevron-left"></span> Back
        <% end %>

        <div id="log_events">
            <%= render 'log' %>
        </div>

    </div>
</div>



<script type="text/javascript">

    function update_log(){
        $.get("/sandthorn/log", {}, function(response){
            $("#log_events").html(response)
        });
    }

    $(document).ready(function(){

        $("#tasked_based").click(function() {
          if ($("#tasked_based").is(':checked'))
          {
            $("#update_button").hide();
          }
          else
          {
            $("#update_button").show();
          }

        });


        $( "#sandthorn_product_name" ).change(function() {
          if ($("#tasked_based").is(':checked'))
          {
            params = { name: $("#sandthorn_product_name").val() };
            $.post("/sandthorn/product/<%= @product.id %>/change_name", params, function(response) {
                update_log();
            });
          }
        });

        $( "#sandthorn_product_price" ).change(function() {
          if ($("#tasked_based").is(':checked'))
          {
            params = { price: $("#sandthorn_product_price").val() };
            $.post("/sandthorn/product/<%= @product.id %>/change_price", params, function(response) {
                update_log();
            });
          }
        });

        $("#sandthorn_product_on_sale_true").change(function(){
            $(".on-sale label").removeClass( "btn-success btn-danger" );
            $(".on-sale label").addClass( "btn-default" );
            $("#sandthorn_product_on_sale_true_label").addClass( "btn-success" );

            if ($("#tasked_based").is(':checked'))
            {
                $.post("/sandthorn/product/<%= @product.id %>/put_on_sale", {}, function(response) {
                    $("#sandthorn_product_name").val(response.name)
                    $("#sandthorn_product_price").val(response.price)
                    update_log();
                });
            }
        });

        $("#sandthorn_product_on_sale_false").change(function(){
            $(".on-sale label").removeClass( "btn-success btn-danger" );
            $(".on-sale label").addClass( "btn-default" );
            $("#sandthorn_product_on_sale_false_label").addClass( "btn-danger" );

            if ($("#tasked_based").is(':checked'))
            {
                $.post("/sandthorn/product/<%= @product.id %>/remove_from_sale", {}, function(response) {
                    $("#sandthorn_product_name").val(response.name)
                    $("#sandthorn_product_price").val(response.price)
                    update_log();
                });
            }
        });

        $( "#sandthorn_product_stock_status_instock" ).change(function() {
          $(".stock-status label").removeClass( "btn-success btn-warning btn-danger" );
          $(".stock-status label").addClass( "btn-default" );
          $("#sandthorn_product_stock_status_instock_label").addClass( "btn-success" );

          if ($("#tasked_based").is(':checked'))
          {
            $.post("/sandthorn/product/<%= @product.id %>/in_stock", {}, function(response) {
                update_log();
            });
          }
        });

        $( "#sandthorn_product_stock_status_outofstock" ).change(function() {
          $(".stock-status label").removeClass( "btn-success btn-warning btn-danger" );
          $(".stock-status label").addClass( "btn-default" );
          $("#sandthorn_product_stock_status_outofstock_label").addClass( "btn-warning" );
          if ($("#tasked_based").is(':checked'))
          {
            $.post("/sandthorn/product/<%= @product.id %>/out_of_stock", {}, function(response) {
                update_log();
            });
          }
        });

        $( "#sandthorn_product_stock_status_discontinued" ).change(function() {
            $(".stock-status label").removeClass( "btn-success btn-warning btn-danger" );
            $(".stock-status label").addClass( "btn-default" );
            $("#sandthorn_product_stock_status_discontinued_label").addClass( "btn-danger" );
          if ($("#tasked_based").is(':checked'))
          {
            $.post("/sandthorn/product/<%= @product.id %>/discontinue", {}, function(response) {
                update_log();
            });
          }
        });
    });
</script>

sandthorn_product_example/app/views/sandthorn/products/index.html.erb
<div class="row editing">
  <div class="col-sm-12">
    <h2>Listing Sandthorn products</h2>
    <p><%= link_to 'New product', new_sandthorn_product_path, class: "btn btn-success" %></p>
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Price</th>
          <th>On Sale</th>
          <th colspan="4">Stock status</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.price %></td>
            <td><%= product.on_sale %></td>
            <td><%= product.stock_status %></td>
            <td><%= link_to 'Show', sandthorn_product_path(product.id), class: "btn btn-xs btn-primary" %></td>
            <td>
              <%= link_to edit_sandthorn_product_path(product.id), class: "btn btn-xs btn-success"  do %>
                <span class="glyphicon glyphicon-edit"></span> Edit
              <% end %>
            </td>
            <td>
              <%= link_to sandthorn_product_path(product.id), method: :delete, confirm: 'Are you sure?', class: "btn btn-xs btn-danger" do %>
                <span class="glyphicon glyphicon-remove-sign"></span> Destroy
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= render 'log' %>
  </div>
</div>

sandthorn_product_example/app/views/sandthorn/products/new.html.erb
<div class="row editing">
    <div class="col-sm-12">
        <h2>New Sandthorn Product</h2>
        <form accept-charset="UTF-8" action="/sandthorn/products" class="new_product" id="new_product" method="post">
          <div style="margin:0;padding:0;display:inline">
            <input name="utf8" type="hidden" value="✓">

            <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
          </div>

          <div class="jumbotron clearfix">
                <div class="form-group clearfix">
                    <label for="sandthorn_product_name" class="col-sm-2 ">Name</label>
                    <div class="col-sm-10">
                        <input id="sandthorn_product_name" name="sandthorn_product[name]" type="text" class="form-control" placeholder="Name">
                    </div>
                </div>
                <div class="form-group clearfix">
                    <label for="sandthorn_product_price" class="col-sm-2 ">Price</label>
                    <div class="col-sm-10">
                        <input id="sandthorn_product_price" name="sandthorn_product[price]" type="text" class="form-control" placeholder="Price">
                    </div>
                </div>
                <div class="col-sm-7">
                    <h4>Stock status</h4>
                    <div class="btn-group btn-group-sm" data-toggle="buttons">
                        <label class="btn btn-success">
                            <input type="radio" name="sandthorn_product[stock_status]" id="sandthorn_product_stock_status_instock" value="instock"> In stock
                        </label>
                        <label class="btn btn-warning">
                            <input type="radio" name="sandthorn_product[stock_status]" id="sandthorn_product_stock_status_outofstock" value="outofstock"> Out of stock
                        </label>
                        <label class="btn btn-danger">
                            <input type="radio" name="sandthorn_product[stock_status]" id="sandthorn_product_stock_status_discontinued" value="discontinued"> Discontinued
                        </label>
                    </div>
                </div>
                <div class="col-sm-5">
                    <p>&nbsp;</p>
                    <input name="commit" type="submit" value="Create Product" class="btn btn-lg btn-block btn-success">
                </div>
            </div>


        </form>
    </div>
</div>

sandthorn_product_example/app/views/sandthorn/products/show.html.erb
<div class="row editing">
  <div class="col-sm-12">
    <h2>Showing Product</h2>
    <div class="jumbotron">
      <p class="lead">
        <strong>Name:</strong>
        <%= @product.name %>
        |
        <strong>Price:</strong>
        <%= @product.price %>
        |
        <strong>Stock status:</strong>
        <%= @product.stock_status %>

        <% if @product.on_sale %>
          |
          <strong>On sale</strong>
        <% end %>
      </p>
    </div>


    <p>
      <%= link_to '<span class="glyphicon glyphicon-chevron-left"></span> Back'.html_safe, "/sandthorn/products/index", class: "btn btn-sm btn-primary"  %>
      | <%= link_to '<span class="glyphicon glyphicon-edit"></span> Edit'.html_safe, "/sandthorn/product/#{@product.id}/edit", class: "btn btn-sm btn-success"  %>
    </p>

    <%= render 'log' %>
  </div>
</div>